function SET_SCALE_OBJ(name, scale)
    Unity:SetScaleObj(name,scale)
end

function SET_DASH(scale)
    Unity:SetDashPlayer(scale)
end

function SET_SPEED(scale)
    Unity:SetSpeedPlayer(scale)
end

function SET_GRAVITY(scale)
    Unity:SetGravityPlayer(scale)
end

function SET_DAGGER_SPEED(scale)
    Unity:SetDaggerSpeed(scale)
end

function SET_COLOR(colorValue)
    Unity:SetColorPlayer(colorValue)
end

function HELP()
    Unity:Help()
end